### ISSUE TITLE
TestLogger.contains vs .matches

### ISSUE THREAD

**Issue by rolandio** [portingle/slf4jtesting#3]
`String` has a method called `contains`. However, the `TestLogger` uses the `contains`-method to silently call `matches`, which is not really intuitive.

Suggestion: introduce a `matches` method, which is a copy of today's `contains`-method and mark the `contains`-method as `@deprecated`. Or, if you don't mind breaking existing code: use `String.contains` instead of `String.matches` inside the `LoggerExtension`-implementation.

**Comment by Johnlon** [comment]
Hi - just seen this request apologies.
Fancy making a pull request?

**Comment by Johnlon** [comment]
Ah - I can see you made a pull request to clear down the loggers.
I've merged that one by the way but I need to get a build out.
Give me a couple of days and I'll see if I can attend to this comment here too.

**Comment by Johnlon** [comment]
See release 1.0.2 - went with the deprecation on contains.
1.0.2 also includes your clear() method.
Thanks again

Let me know if any problems.
