### ISSUE TITLE
Utility class to circumvent the need for DI of the ILoggerFactory

### ISSUE THREAD

**Issue by adam42a** [portingle/slf4jtesting#8]
I didn't want to change over the Logger initialization to DI so I wrote little utility to allow myself to stay with the usual way:

    private final Logger log = LoggingUtils.getLogger(Example1.class);

    public class LoggingUtils {

        private LoggingUtils() { }
        
        private static ILoggerFactory ILoggerFactory = 
                LoggerFactory.getILoggerFactory();
    
        public static void switchToTestLogging() {
            ILoggerFactory = new TestLoggerFactory();
        }
    
        public static Logger getLogger(Class loggingClass) {
            return ILoggerFactory.getLogger(loggingClass.getName());
        }
    }

It does require compile-time scope for the dependency but just put it in a utility jar with SLF4jTesting as an optional dependency so it doesn't get pulled into the production jars/wars. 

    <project>
        <groupId>com.megacorp</groupId>
        <artifactId>my-utilities</artifactId>
        <version>1.2.3</version>
        <packaging>jar</packaging>
        <dependencies>
            <dependency>
                <groupId>com.portingle</groupId>
                <artifactId>slf4jtesting</artifactId>
                <version>1.1.3</version>
                <scope>compile</scope>
                <optional>true</optional>
            </dependency>

HTH

**Comment by Johnlon** [comment]
Hi thanks for the feedback.
I understand what you are trying to achieve and I'm pleased you are able to get benefits from the testing double that slf4jtesting provides.

Hope you don't mind me commenting further...

This pattern still relies on a static and so will still suffer from many of the problems that slf4jtesting was written to help address more generally, such as difficulties with running tests in parallel. Ideally each parallel test would have its own local instance of the logging infra but this is only possible if we use dependency injection into the subject under test , ... or if we use a separate class loader for each parallel test.

The "one class loader per test" approach actually works ok I found, but it's more magic and more brittle than simply using DI for the logging implementation.

I had a OneClassLoaderPerTest stackable trait at one point that I wrote for scalatest that I used for a while.

But in the end I just switched to constructor injection for the logging implementation in the same way I do for all my other services.

Clearly ctor Injection is achieveable with things like Spring but I'm one of those Scala programmers who prefers a "no framework" approach to assembly. 
However, if you don't mind frameworks then use spring et al and inject the real logging in prod and  the test double in tests.

Please let me know if there are any API enhancements that are useful to you.

Thanks again John

PS I'll close this ticket if that's ok with you. Rsvp

**Comment by adam42a** [comment]
Sure close it - it's not an issue anyway since it wouldn't go in the code base of slf4jtesting if wanted. 

I'm still scratching my head then what the issue with concurrency would be. Surely the DI framework (and certainly a Spring context) would just inject a singleton LoggerFactory? Whether you inject it in the constructor or as above, it seems the implications for concurrency are the same?

**Comment by Johnlon** [comment]
Each test would construct it's own instance of the test subject and the log implementation and throw them away after the test. As the objects are local to each test then there is no problem running tests concurrently.
If I was using spring then each test would construct a distinct application context so again each test would have its own instance of the subject and log implementation.

No sharing between test cases at all.

**Comment by adam42a** [comment]
OK I see, you go in for slow torture. When I find a more lightweight DI framework than Spring, I would reconsider doing that - and searching for one might be a direct result of logging getting messed up in concurrent unit tests. I'll close this then, I take your points.

**Comment by Johnlon** [comment]
Hi, I don't use spring, I go in for the torture of no frameworks.
I was merely suggested how it was intended to work in a parallel test suite with or without a DI framework, using spring as an illustration to make it concrete.
