### ISSUE TITLE
Customizable layout for console output

### ISSUE THREAD

**Issue by tekumara** [portingle/slf4jtesting#9]
It would be nice to be able to customise the `layout` method in `LoggerExtensionsImpl` so the console output can be made to match the pattern layout I'm using.

**Comment by Johnlon** [comment]
Do you have an API in mind?

**Comment by bongogames** [comment]
Hi @tekumara did you have any thoughts on the api?
Or a pull request.

**Comment by Johnlon** [comment]
It is already possible.
See the example code here.
https://github.com/portingle/slf4jtesting/blob/master/src/test/java/demos/Example4/Example.java
